# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTest:
    def __init__(self,driver):
        self.driver=driver

    def teardown_method(self, method):
        self.driver.quit()

    def test_test(self):
        self.driver.get("https://nutriwest.staging.genetechz.com/")
        self.driver.set_window_size(1936, 1056)
        self.driver.find_element(By.LINK_TEXT, "About Nutri-West").click()
        self.driver.find_element(By.LINK_TEXT, "Seminars").click()
        self.driver.find_element(By.LINK_TEXT, "View More").click()
        self.driver.find_element(By.LINK_TEXT, "Contact Us").click()
        self.driver.find_element(By.NAME, "email").click()
        self.driver.find_element(By.NAME, "email").send_keys("tester@yopmail.com")
        self.driver.find_element(By.NAME, "first_name").click()
        self.driver.find_element(By.NAME, "first_name").send_keys("tester")
        self.driver.find_element(By.NAME, "last_name").click()
        self.driver.find_element(By.NAME, "last_name").send_keys("tester")
        self.driver.find_element(By.NAME, "subject").click()
        self.driver.find_element(By.NAME, "subject").send_keys("no subject")
        self.driver.find_element(By.NAME, "message").click()
        self.driver.find_element(By.NAME, "message").send_keys("test message")
        self.driver.find_element(By.ID, "btnSubmit").click()
        self.driver.switch_to.frame(1)
        self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-border").click()
        self.driver.switch_to.default_content()
        self.driver.find_element(By.ID, "btnSubmit").click()

s = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=s)
p1=TestTest(driver)
p1.test_test()